name: Continuous Integration

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: "1"
    steps:
      - name: Set up Go 1.18
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
        id: go

      - name: Checkout code
        uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.1.0
      - name: Build Linux binary amd64
        run: make build