name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: "1"
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
        id: go

      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.43.0
      - name: Run linter
        run: make lint
      - name: Build Linux binary amd64
        run: make build